### ISSUE TITLE
No Faces Detected in Target Preview Window

### ISSUE THREAD

**Issue by Orchoidizer** [C0untFloyd/roop-unleashed#207] opened 2023-09-11 03:28 UTC
**Describe the bug**
No face detected in target preview window (the retuen of a previous bug!)

1. Go to 'add target file'
2. Click on 'use face from this frame'
4. See error - Info - No Faces Detected

- [11 ] Windows 

Are you using a GPU?
- [x ] NVIDIA
- 
roop unleashed 3.0.2

**Comment by Niiickel** [comment] 2023-09-11 12:37
Tried it with another file or a different frame? Because it's working just fine on my installation with win 10 and nvidia gpu

**Comment by dedkamaroz** [comment] 2023-09-11 13:05
This issue seems to be impacting only video files.
Using image files as the target is working for me, but using video files (tried mp4/mov encoded as AVC format/codec) and the Preview Image box stays blank no matter which button is pressed.
Also there's no message appearing the command prompt in the background..

I don't actually get the "No Faces Detected" error however, the application simply responds to button clicks as if I have not yet uploaded a target file.

[10] Windows
[x] NVIDIA
roop unleased 3.0.2

I installed twice, once via the batch file, and 2nd time via pip/requirements.txt using a new Conda env.

Let me know if you need any log files or browser dev tools dumps to assist.

**Comment by C0untFloyd** [comment] 2023-09-11 16:19
It might have been caused by the endframe bug in v3.0.2 or a very close, zoomed face. Please update and let me know.

**Comment by dedkamaroz** [comment] 2023-09-12 08:21
> It might have been caused by the endframe bug in v3.0.2 or a very close, zoomed face. Please update and let me know.

Thank you so much for being so quick to attempt resolving issues.. Unfortunately the 3.0.5 update didn't resolve the issue.

Steps I took:
1. Downloaded the models zip and replaced the existing models with the zip contents
2. Started roop-unleashed via "python run.py" from within the Conda env
3. Added source face image (face detected)
4. Added video (face not detected):
    - Face in video is about 2m away from camera    
5. After video uploaded, the Preview Image frame flashed for a split second with a progress bar but then immediately reverted to its standard blank state with the icon of a photo in the center
6. None of the buttons/toggles under this frame do anything other than repeating step 5 each time
7. Clicking Start simply lists all the files currently in the Output Folder

I tried in both Chrome and Firefox - same behaviour.

Please let me know if you need any further info
Thanks again!

**Comment by lysxelapsed** [comment] 2023-09-12 09:57
have you tried a system restart / checked running tasks? happened to me when python didn't close properly and ran in the background. running a second instance of python / roop-unleashed produced the error in my case.

**Comment by C0untFloyd** [comment] 2023-09-12 12:00
Never ever had this happening. Can you try with CPU-only (restart the whole app after changing and applying settings). And try pasting the console output here, there MUST be some kind of exception somewhere...

**Comment by Orchoidizer** [comment] 2023-09-14 22:47
Updated the uinstall and all good now. Thanks for this amazing tool!

**Comment by Orchoidizer** [comment] 2023-09-14 22:51
Updated the uinstall and all good now. Thanks for this amazing tool!

**Closed** 2023-09-15 05:56 UTC
